using System;
using System.Collections.Generic;
using Peliculas.Shared.Entidades;

namespace Peliculas.Client.Servicios
{
    public class ServicioPelicula: IserviciosPeliculas
    {
        public List<Pelicula> GetPelicula(){
            return new List<Pelicula> (){
                new Pelicula(){Imagen="/Imagenes/PelCruella.jpg",Nombre="Cruella",Sinopsis="Ambientada en el Londres de los años 70, en plena revolución del punk rock, muestra a una joven estafadora llamada Estella, una chica inteligente y creativa, decidida a convertirse en una exitosa diseñadora de moda, que se asocia con un par de ladrones para sobrevivir en las calles de la capital británica. Pero cuando su talento para la moda llama la atención de la legendaria diseñadora, la Baronesa von Hellman, Estella cambia el rumbo de su vida hasta que una serie de acontecimientos y revelaciones que harán que Estella asuma su lado malvado y se convierta en la estridente, moderna y vengativa Cruella de Vil.",Puntaje="83/100",Lanzamiento = new DateTime(2021,05,28),Director="Craig Gillespie"},
                new Pelicula(){Imagen="/Imagenes/PelEscuadron.jpg",Nombre="El escuadrón suicida",Sinopsis="Un grupo de super villanos se encuentran encerrados en Belle Reve, una prisión de alta seguridad con la tasa de mortalidad más alta de Estados Unidos. Para salir de allí harán cualquier cosa, incluso unirse al grupo Task Force X, dedicado a llevar a cabo misiones suicidas bajo las órdenes de Amanda Waller. Fuertemente armados son enviados a la isla Corto Maltese, una jungla repleta de enemigos.",Puntaje="79/100",Lanzamiento = new DateTime(2021,08,06),Director="James Gunn"},
                new Pelicula(){Imagen="/Imagenes/PelGuardianes.jpg",Nombre="Guardianes de la Noche: Tren infinito",Sinopsis="Tanjiro y sus compañeros se unen al Pilar de las Llamas Kyojuro Rengoku para investigar una misteriosa serie de desapariciones que han ocurrido dentro del “Tren Infinito”. Poco saben que Enmu, uno de los miembros de las Doce Lunas Demoníacas, también está a bordo y les ha preparado una trampa.",Puntaje="84/100",Lanzamiento = new DateTime(2021,04,23),Director="Haruo Sotozaki"},
                new Pelicula(){Imagen="/Imagenes/PelJungle.jpg",Nombre="Jungle Cruise",Sinopsis="Principios del siglo XX. Frank es el carismático capitán de una peculiar embarcación que recorre la selva amazónica. Allí, a pesar de los peligros que el río Amazonas les tiene preparados, Frank llevará en su barco a la científica Lily Houghton y a su hermano McGregor Houghton. Su misión será encontrar un árbol místico que podría tener poderes curativos. Claro que su objetivo no será fácil, y en su aventura se encontrarán con toda clase de dificultades, además de una expedición alemana que busca también este árbol con propiedades curativas. Esta comedia de acción y aventuras está basada en la atracción Jungle Cruise de los parques de ocio de Disney.",Puntaje="78/100",Lanzamiento = new DateTime(2021,07,30),Director="Jaume Collet-Serra"},
                new Pelicula(){Imagen="/Imagenes/PelKate.jpg",Nombre="Kate",Sinopsis="Tras ser envenenada sin remedio, una implacable criminal tiene menos de 24 horas para vengarse de sus enemigos y, durante el proceso, se forma un vínculo inesperado con la hija de una de sus víctimas anteriores.",Puntaje="68/100",Lanzamiento = new DateTime(2021,09,10),Director="Cedric Nicolas-Troyan"},
                new Pelicula(){Imagen="/Imagenes/PelLaGuerra.jpg",Nombre="La guerra del mañana",Sinopsis="Un día el mundo se paraliza cuando un grupo de viajeros en el tiempo se transporta desde el año 2051 para entregar un mensaje urgente: La humanidad está perdiendo la guerra mundial contra una especie alienígena letal. La única esperanza de supervivencia es que los soldados y los ciudadanos del presente sean transportados al futuro y se unan a la lucha. Entre los reclutados está el profesor de instituto y padre de familia Dan Forester (Chris Pratt) quien, decidido a salvar el mundo por su hija, se une a una brillante científica (Yvonne Strahovski) y a su padre (J.K. Simmons) en una búsqueda desesperada por reescribir el destino del planeta.",Puntaje="81/100",Lanzamiento = new DateTime(2021,07,02),Director="Chris McKay"},
                new Pelicula(){Imagen="/Imagenes/PelPatrulla.jpg",Nombre="La patrulla canina: la película",Sinopsis="La patrulla canina está en racha. Cuando Humdinger, su mayor rival, se convierte en alcalde de la cercana Ciudad Aventura y empieza a causar estragos, Ryder y los heroicos cachorros se ponen en marcha para enfrentarse a este nuevo desafío. Mientras uno de los cachorros debe enfrentarse a su pasado en Ciudad Aventura, el equipo encuentra ayuda en una nueva aliada, la inteligente perrita salchicha Liberty. Juntos y armados con nuevos y emocionantes artefactos y equipos, la patrulla canina lucha por salvar a los ciudadanos de Ciudad Aventura.",Puntaje="79/100",Lanzamiento = new DateTime(2021,08,20),Director="Cal Brunker"},
                new Pelicula(){Imagen="/Imagenes/PelRapidoFurioso.jpg",Nombre="Fast & Furious 9",Sinopsis="Dom Toretto lleva una vida tranquila con Letty y su hijo, el pequeño Brian, pero saben que el peligro siempre acecha. Esta vez, esa amenaza obligará a Dom a enfrentarse a los pecados de su pasado si quiere salvar a quienes más quiere. El equipo se vuelve a reunir para impedir un complot a escala mundial, liderado por uno de los asesinos más peligrosos y mejor conductor a los que se han enfrentado; un hombre que además es el hermano desaparecido de Dom, Jakob. Novena entrega de la famosa franquicia.",Puntaje="75/100",Lanzamiento = new DateTime(2021,06,25),Director="Justin Lin"},
                new Pelicula(){Imagen="/Imagenes/PelSpaceJam.jpg",Nombre="Space Jam: Nuevas Leyendas",Sinopsis="Secuela de la cinta original de 1996, Space Jam, protagonizada por Michael Jordan. En esta segunda parte, la super estrella de la NBA es LeBron James, quien queda atrapado junto a su hijo Dom en un extraño lugar, un espacio digital de una fuerza todopoderosa y malvada conocida como A.I. Para volver a casa y poner a salvo a su hijo, el jugador de baloncesto deberá unir fuerzas con Bugs Bunny, Lola Bunny y el resto de personajes de los Looney Tunes para enfrentarse en un partido de baloncesto a los campeones digitalizados por inteligencia artificial.",Puntaje="74/100",Lanzamiento = new DateTime(2021,07,16),Director="Terence Nance"},
                new Pelicula(){Imagen="/Imagenes/PelSweetGirl.jpg",Nombre="Sweet Girl",Sinopsis="Un marido destrozado jura llevar ante la justicia a los responsables de la muerte de su mujer, a la vez que protege a la única familia que le queda, su hija.",Puntaje="69/100",Lanzamiento = new DateTime(2021,08,18),Director="Brian Andrew Mendoza"}
            };
        }
    }
}