using Peliculas.Shared.Entidades;
using System.Collections.Generic;
using System;
namespace Peliculas.Client.Servicios
{
    public class ServicioActor: IservicioActor
    {
        public List<Actor> GetActores()
        {
            return new List<Actor>{
                new Actor(){NombreActor ="Jason Momoa",TipoDocumento=TipoDocumento.CedulaCiudadana,Documento="33822547",Genero=Genero.Masculino,FechaNacimiento= new DateTime(1979,08,01),Nominaciones = 43,Biografia = "Joseph Jason Namakaeha Momoa (1 de agosto de 1979) es un actor, escritor, productor, director y modelo estadounidense.Es conocido por interpretar a Aquaman en el Universo extendido de DC Comics, comenzando con la película de superhéroes Batman v Superman: Dawn of Justice en 2016, y en el conjunto de Liga de la Justicia en 2017 y su película individual Aquaman en 2018. También es conocido por sus papeles televisivos como Ronon Dex en la serie de televisión de ciencia ficción militar Stargate Atlantis (2004-2009), como Khal Drogo en la serie de televisión de fantasía de HBO Game of Thrones (2011-2012) y como Declan Harp en la serie de Netflix Frontier (2016-presente)."},
                new Actor(){NombreActor ="Isabela Merced",TipoDocumento=TipoDocumento.CedulaCiudadana,Documento="822331058",Genero=Genero.Femenino,FechaNacimiento= new DateTime(2001,07,10),Nominaciones = 19,Biografia = "Isabela Merced (born Isabela Yolanda Moner on July 10, 2001) is an American actress, voice actress, singer, songwriter, dancer and ukulele player. Moner was born in Cleveland, Ohio. She was born to Katherine Moner, of Peruvian descent, who was born in Lima, Peru and to Patrick Moner, of American descent, who was born in Louisiana. She is the middle child of her family and has two other brothers, Gyovanni, which is her younger brother and Jared, which is her older brother. She had her Broadway debut at the age of 10 in a production of Evita."},
                new Actor(){NombreActor ="Woody Harrelson",TipoDocumento=TipoDocumento.CedulaCiudadana,Documento="25548799",Genero=Genero.Masculino,FechaNacimiento= new DateTime(1961,07,23),Nominaciones = 140,Biografia = "Tras su graduación se trasladó a Nueva York y comenzó a estudiar en el Biloxi Blues de Neil Simon. En 1985 fue elegido para el papel de Woody Boyd, el ingenuo y cordial camarero de la serie de televisión Cheers, con el que ganó un Emmy, entre otros premios. Su primera actuación en el cine fue en la película Gatos salvajes de 1986 junto a Goldie Hawn. Continuó trabajando con pequeños papeles en el cine hasta el enfrentamiento amoroso que protagonizó con Michael J. Fox en la película de 1991, Doc Hollywood. Posteriormente Harrelson trabajó en películas como Asalto al tren del dinero, La cortina de humo, White Men Can't Jump, Vaqueros de Nueva York, Indecent Proposal, Hi-Lo Country y Natural Born Killers de Oliver Stone de 1994, donde interpreta a un despiadado asesino."},
                new Actor(){NombreActor ="Mary Elizabeth Winstead",TipoDocumento=TipoDocumento.CedulaCiudadana,Documento="633226584",Genero=Genero.Femenino,FechaNacimiento= new DateTime(1984,11,28),Nominaciones = 64,Biografia = "Mary Elizabeth Winstead (n. Rocky Mount, Carolina del Norte, 28 de noviembre de 1984) es una actriz, cantante y modelo estadounidense conocida por sus papeles en películas como Sky High, Death Proof, Bobby, Black Christmas, Destino final 3, Live Free or Die Hard y Scott Pilgrim vs. The World, y por su papel protagónico en la serie The Returned. Fue nominada para el Young Artist Award por su actuación en Passions."},
                new Actor(){NombreActor ="Dwayne Johnson",TipoDocumento=TipoDocumento.CedulaCiudadana,Documento="64885520",Genero=Genero.Masculino,FechaNacimiento= new DateTime(1972,05,02),Nominaciones = 271,Biografia = "Dwayne Douglas Johnson (2 de mayo de 1972) es un actor y luchador profesional estadounidense, conocido popularmente como The Rock (La Roca​ en español). Se desempeñó como luchador profesional para la WWE hasta su retirada oficial en 2019, con el objetivo de centrarse en su carrera artística. Ha participado en una gran diversidad de películas siendo premiado en muchas de ellas, siendo su papel como Luke Hobbs en The Fast and the Furious uno de los más reconocidos. Entre sus logros como luchador se destacan diez Campeonatos Mundiales: ocho como Campeón de la WWE y dos como Campeón de la WCW. También fue dos veces Campeón Intercontinental de la WWE y cinco veces Campeón Mundial en Parejas. También fue el ganador del Royal Rumble 2000 todo esto lo vuelve Campeón de las Tres Coronas. Es famoso por acabar todos sus discursos en el cuadrilátero y al presentarse en escena con la frase: 'If you smell... What The Rock is Cooking?' que se puede traducir como: ¿Pueden oler... Lo que está cocinando la Roca? Esta frase es una variación de pregunta-respuesta, un modismo de palabras que pretende hacer un juego con el público, en una pregunta, '¿Si puedes oler?' y el público responde a modo de coro, 'Lo que la roca está cocinando', o también usa la Frase: Finally, The Rock is come back.... y da una referencia de la ciudad donde se encuentra. El primer papel protagonista de Johnson en una película fue en The Scorpion King en 2002. Por esto, le pagaron $ 5.5 millones, un récord mundial para un actor en su primer papel protagónico. Uno de sus papeles más prominentes es Luke Hobbs en la franquicia The Fast and the Furious. Además organizó y produjo The Hero, una serie de reality shows y desde entonces ha seguido produciendo programas de televisión y películas a través de su productora Seven Bucks Productions.En 2013, La revista Forbes nombró a Johnson el No. 25 entre las 100 celebridades más poderosas y ha estado entre los mejores veinte desde entonces. Fue el actor mejor pagado del mundo en el 2016. La revista Time lo nombró una de las 100 personas más influyentes del mundo en 2016. En 2015, La revista Muscle & Fitness lo nombró el 'Hombre del siglo'."},
                new Actor(){NombreActor ="Emily Blunt",TipoDocumento=TipoDocumento.CedulaCiudadana,Documento="35556588",Genero=Genero.Femenino,FechaNacimiento= new DateTime(1983,02,23),Nominaciones = 96,Biografia = "Emily Olivia Leah Blunt (born 23 February 1983) is a British actress. Her accolades include a Golden Globe Award and a Screen Actors Guild Award, in addition to nominations for two British Academy Film Awards. Educated at Hurtwood House in Dorking, Blunt made her acting debut in a 2001 stage production of The Royal Family. She went on to appear in the television film Boudica (2003) and portrayed Queen Catherine Howard in the miniseries Henry VIII (2003). She made her feature film debut in the drama My Summer of Love (2004). Blunt's breakthrough came in 2006 with her starring roles in the television film Gideon's Daughter and the comedy-drama film The Devil Wears Prada. The former won her a Golden Globe Award for Best Supporting Actress and the latter earned her a nomination for the BAFTA Award for Best Actress in a Supporting Role. Blunt's profile continued to grow with leading roles in the period film The Young Victoria (2009), the romantic comedy Salmon Fishing in the Yemen (2011), the science fiction films The Adjustment Bureau (2011), Looper (2012), and Edge of Tomorrow (2014), and the musical films Into the Woods (2014) and Mary Poppins Returns (2018). She received critical acclaim for playing a principled FBI agent in the crime film Sicario (2015), an alcoholic in the thriller The Girl on the Train (2016), which earned her a nomination for the BAFTA Award for Best Actress in a Leading Role, and a survivalist mother in the horror film A Quiet Place (2018). For the latter, which was directed by her husband John Krasinski, she won the Screen Actors Guild Award for Best Supporting Actress."},
                new Actor(){NombreActor ="Margot Robbie",TipoDocumento=TipoDocumento.CedulaCiudadana,Documento="13266114",Genero=Genero.Femenino,FechaNacimiento= new DateTime(1990,07,02),Nominaciones = 58,Biografia = "Es una actriz, modelo y productora australiana, más conocida por haber interpretado a Donna Freedman en la serie Neighbours, a Naomi Belfort en la película El lobo de Wall Street, a Jane Porter en la película La leyenda de Tarzán, a Harley Quinn en la película de villanos Escuadrón Suicida de DC Comics y a Tonya Harding en el biopic I, Tonya."},
                new Actor(){NombreActor ="Sylvester Stallone",TipoDocumento=TipoDocumento.CedulaCiudadana,Documento="6485700",Genero=Genero.Masculino,FechaNacimiento= new DateTime(1946,07,06),Nominaciones = 170,Biografia = "Michael Sylvester Gardenzio Stallone (6 de julio de 1946) es un actor, guionista, productor y director de cine estadounidense, estrella del cine de acción de Hollywood. Ha dado vida a tres personajes icónicos de la historia del cine: a Rocky Balboa, un boxeador de Filadelfia que venció contra todo pronóstico y se convirtió en campeón; a John Rambo, ex boina verde veterano de la guerra de Vietnam, especializado en guerrilla, supervivencia y combate, y a Barney Ross, también un veterano de la Guerra del Vietnam y líder de un grupo de mercenarios veteranos y novatos, contratados para operaciones de espionaje y militares. La cinta Rocky (1976) le valió dos nominaciones al premio Óscar, en la categoría de Mejor Actor y Mejor Guion. En 2016 ganó el Globo de Oro a Mejor actor de reparto por el papel de Rocky Balboa en el spin-off de la saga, Creed (2015), además de ser nominado al Óscar en la misma categoría."},
                new Actor(){NombreActor ="Natsuki Hanaea",TipoDocumento=TipoDocumento.CedulaCiudadana,Documento="663322584129",Genero=Genero.Masculino,FechaNacimiento= new DateTime(1991,06,26),Nominaciones = 111,Biografia = "Natsuki Hanae is a Japanese voice actor from Kanagawa Prefecture. He is affiliated with Across Entertainment. In 2015, he won an award at the 9th Seiyuu Awards as one of the best male newcomers. He also hosts the radio show ŌHana (逢坂市立花江学園 Ōsaka Shiritsu Hanae Gakuen) along with voice actor Ryōta Ōsaka. 'Hanae' is actually a pseudonym; his real surname has not been disclosed by his agency."},
                new Actor(){NombreActor ="Emma Stone",TipoDocumento=TipoDocumento.CedulaCiudadana,Documento="112003648585",Genero=Genero.Femenino,FechaNacimiento= new DateTime(1988,11,06 ),Nominaciones = 68,Biografia = "Emily Jean «Emma» Stone (Scottsdale, Arizona, 6 de noviembre de 1988) es una actriz y cantante estadounidense. Ha recibido numerosos premios, entre ellos: un Óscar, un BAFTA, un SAG y un Globo de Oro, a mejor actriz, por su interpretación en la cinta La La Land. Adicionalmente ha ganado la Copa Volpi. Además es considerada como una de las mejores actrices de su generación. Comenzó su carrera apareciendo en obras teatrales en el Valley Youth Theatre de Phoenix como Las aventuras de Alicia en el país de las maravillas y Joseph and the Amazing Technicolor Dreamcoat, y debutó en televisión en The New Partridge Family (2005), sin embargo, solo se produjo un episodio piloto.​ Su primer papel en cine se dio en la comedia de Greg Mottola Superbad (2007), junto a Michael Cera y Jonah Hill.​ Obtuvo reconocimiento por sus trabajos posteriores en producciones como easy A (2010) y The Help (2011) en las cuales fue protagonista y que determinaron excelentes críticas para la actriz."},
                new Actor(){NombreActor ="Iain Armitage",TipoDocumento=TipoDocumento.CedulaCiudadana,Documento="22326255458",Genero=Genero.Masculino,FechaNacimiento= new DateTime(2008,07,15),Nominaciones = 13,Biografia = "Iain Armitage is an American child actor. He is best known for Young Sheldon, a prequel to the sitcom The Big Bang Theory and the HBO miniseries Big Little Lies. He also appeared in the films The Glass Castle (2017) and Our Souls at Night (2017). His acting debut was in an episode of Law & Order: Special Victims Unit."}
            };
        }
    }
}